#!/bin/bash

Rid1=0xd54731af
Rid2=0xc1bbb55e

# Mise en place tunnel sur h1 (SA)
ip xfrm state add src 10.10.10.1 dst 10.0.0.1 proto esp spi "@SPI1" reqid\
"@Rid1" mode tunnel auth sha256 "@K1" enc aes "@K2"
ip xfrm state add src 10.0.0.1 dst 10.10.10.1 proto esp spi "@SPI2" reqid\
"@Rid2" mode tunnel auth sha256 "@K3" enc aes "@K4"

# Mise en place règle sur h1 (SP)
ip xfrm policy add src 10.10.10.1 dst 10.0.0.1 dir in tmpl src 10.10.10.1 dst 10.0.0.1 proto esp reqid "$Rid1" mode tunnel
ip xfrm policy add src 10.0.0.1 dst 10.10.10.1 dir out tmpl src 10.0.0.1 dst 10.10.10.1 proto esp reqid "$Rid2" mode tunnel

# Mise en place règle sur h2 (SP)
ip xfrm policy add src 10.0.0.1 dst 10.10.10.1 dir in tmpl src 10.0.0.1 dst 10.10.10.1 proto esp reqid "$Rid1" mode tunnel
ip xfrm policy add src 10.10.10.1 dst 10.0.0.1 dir out tmpl src 10.10.10.1 dst 10.0.0.1 proto esp reqid "$Rid2" mode tunnel